### ISSUE TITLE
关于Trade Detail行情数据存入MongoDB的问题

### ISSUE THREAD

**Issue by chanson-chan** [hadrianl/huobi#3]
Trade Detail返回的数据msg['tick‘]['data’]列表中的‘id‘字段因为是整数，太长导致插入MongoDB时会报错，得转为str再插入

而且into_db中对depth的数据没处理呀

**Comment by chenchensheng** [comment]
稍微改了一下
    def into_db(self, data, topic: str):
        collection = self.db.get_collection(topic)
        try:
            if 'kline' in topic:
                if isinstance(data, dict):
                    collection.update({'id': data['id']}, data, upsert=True)
                elif isinstance(data, list):
                    for d in data:
                        collection.update({'id': d['id']}, d, upsert=True)
            elif 'trade.detail' in topic:
                for d in data['data']:
                    d['id'] = str(d['id'])  # id 过长MongoDB不支持，需转为str
                collection.insert_one(d)
            elif 'depth' in topic:
                collection.update({'version': data['version']}, data, upsert=True)
        except Exception as e:
            logger.error(f'<数据>插入数据库错误-{e}')

**Comment by hadrianl** [comment]
好的，已收到邮件，稍后会更新过来的，但是depth的数据里面有存在version这个字段吗？

**Comment by hadrianl** [comment]
调试了一下，depth里面的ts和version两个字段怎么理解？

**Comment by chanson-chan** [comment]
ts肯定是时间戳，至于version我也很困惑为什么要多这个字段出来，目前来看这两个字段的表现是一样的，ts相等的数据version也相等

**Comment by hadrianl** [comment]
不一定，我看了，version应该是唯一标识，有存在version相同，ts不同的情况的，虽然比较少
