### ISSUE TITLE
交易客户端实现

### ISSUE THREAD

**Issue by sfzhang** [hadrianl/huobi#6]
`WebSocketApp.run_forever()`会进入无限循环，如果要和客户端（`PyQt`）比如进行交互（展示KLine，发送新的订阅请求给服务器）时，如何处理更好呢？使用`QLocalSocket`？或者有更合适的方案。谢谢！
默认情况下，`WebSocketApp`发送不是线程安全的，意味不加锁情况下不能在一个线程发送心跳包，另外一个线程发送请求。

**Comment by hadrianl** [comment]
我理解您的意思是基于huobitrade架设一个服务器，然后另外写个客户端与服务器交互？如果是这个意思的话，我觉得这里[https://github.com/hadrianl/huobi/blob/master/huobitrade/extra/rpc.py]可能提供一些小参考（虽然并不是很成熟的解决方案），采用的是zmq来做订阅发布和请求。

**Comment by hadrianl** [comment]
但是实际上我个人并不推荐这样的去做，我觉得websocketapp应该是集成在客户端中，直接对接火币的服务器。如果是这样的话，那一个客户端实例化一个websocketapp。那写好一个handler就能实现一些如kline展示之类的了，实现方法可选也挺多的，如果用pyqt的话，我觉得pyqtSignal是个不错的选择，写个QObject在handler的handle函数里把数据emit出来，kline展示这边直接绑定这个signal。之前写过一个恒指交易的服务端与客户端，可以看这里服务端[https://github.com/hadrianl/spapi]和这里客户端[https://github.com/hadrianl/hseng_pyqt]。我是觉得用signal就好了，没有进程间的通讯，QLocalSocket好像没有必要？

**Comment by sfzhang** [comment]
OK，十分感谢。确实可以使用signal/slot实现
