### ISSUE TITLE
订阅行情超过24小时左右的时候，就会接受不到消息

### ISSUE THREAD

**Issue by aquarius-wing** [hadrianl/huobi#7]
接收不到的时候，进程还在，但是并没有执行对应的callback方法，这个是怎么回事？

**Comment by hadrianl** [comment]
信息不多，暂时不清楚导致这问题的原因。尽量选择境外服务器，在保持pingpong应答的情况下且订阅的topic不多的情况下，一般不会接收不到行情的。这跟火币的行情服务器的保活的机制也有一定关系吧

**Comment by aquarius-wing** [comment]
我的服务器是阿里上买的香港服务器，ping火币服务器有稳定2.0几ms，请问还什么调试方法可以用来排查问题吗？

**Comment by hadrianl** [comment]
这个可能跟链路的关系不大，可以把logger的level设置成debug模式，能收到全部信息。如果有debug的msg，但是callback里面没有输出的话那可能是你的callback函数的问题。尽量不要让callback执行耗时的操作，尽早分发或处理完，callback实际上是放在线程池（max=3）里面执行的，耗时太多的操作不要再callback里面做。特别是有阻塞的操作，如果3个线程都被阻塞了，后面的线程就一直处于pending状态，不会执行了

**Comment by aquarius-wing** [comment]
好的，我去试试，谢谢解答🙏

**Comment by aquarius-wing** [comment]
最近又跑了一次，日志如下（已经设置DEBUG级别了），大佬有空看一下？

```
2019-11-28 17:54:00,731/1574934840.731141:INFO:[Sub][1] Connecting...
2019-11-28 17:54:00,968/1574934840.968513:INFO:[Sub][1] Connected to server
2019-11-30 02:12:46,019/1575051166.019221:INFO:[Sub][1] Connection event loop down
```
